name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25
      with:
        arguments: build
    
    - name: Build and Push Docker images
      uses: mr-smithers-excellent/docker-build-push@v4
      with:
        image: obiwan6123/demo-app
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}




# # This workflow will build a Java project with Gradle
# # For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

# name: Java CI with Gradle

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build-java:

#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up JDK 1.8
#       uses: actions/setup-java@v1
#       with:
#         java-version: 1.8

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew

#     - name: Build with Gradle
#       run: ./gradlew build

#     - name: Build and Push Docker Image
#       uses: mr-smithers-excellent/docker-build-push@v4
#       with:
#         image: nanajanashia/demo-app
#         registry: docker.io
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
         
